hemant_dbt:
  outputs:
    dev:
      catalog: dbt_tutorial_dev
      host: 
      http_path: /sql/1.0/warehouses/37f5f654655d0301
      schema: default
      threads: 1
      token: 
      type: databricks
  target: dev
