hemant_dbt:
  outputs:
    dev:
      catalog: dbt_tutorial_dev
      host: dbc-c17907d6-ea65.cloud.databricks.com
      http_path: /sql/1.0/warehouses/37f5f654655d0301
      schema: default
      threads: 1
      token: dapi3ede095cebacde15284c96c2ca62dc1a
      type: databricks
  target: dev
